- .nvmrc
- README.md
- package-lock.json
Noté que el pkg no corría con versiones de node no LTS, así que agregué un nvmrc
```
npm run build
> wollok-ts-cli@0.0.1 build
> rm -rf dist && tsc && pkg .
> pkg@5.6.0
> Targets not specified. Assuming:
node15-linux-x64, node15-macos-x64, node15-win-x64
> Error! No available node version satisfies 'node15'
```
Solución aquí:
https://github.com/vercel/pkg/issues/838#issuecomment-805048225
> Agrego nvmrc

- src/commands/repl.ts
Respondiendo a una de las tareas pendientes en #19 este commit busca resolver el problema de que el anterior refactor generaba errores "feos" al inicializar o reiniciar el repl si el archivo a validar tenía errores.
Debo justificar la linea 90. Al final tome la decisión de hacer process.exit() ya que como deseamos imprimir el error de forma bonita, tras catchearlo y hacerlo, la función puede continuar y esto es feo porque terminas con un repl con errores, si se hace un throw falla de forma fea y si se ataja en otro lado estamos trasladando el mismo problema. Solución: hacer el equivalente a ':q' tras mostrar el error y justamente ahí se llama a process.exit() por eso es que llegué a la conclusión de que sí había que usarlo.
> Command repl reload errors

- package.json
`npm build` script requires the `./build` directory to exist, it seems this command had already been part of the script but was accidentally deleted.
> build script fix

- .eslintrc
- package-lock.json
- package.json
- src/commands/extrasGame.ts
- src/commands/repl.ts
- src/commands/run.ts
- src/commands/test.ts
- src/utils.ts
- test/repl.test.ts
- tsconfig.build.json
- tsconfig.json
Here is a migration to use `wollok-ts@4.0.1`.
A superficial manual test seems to indicate that the changes didn't break anything (we really need to add some E2E to this...) and only a few tests are not passing but I'm not sure those tests expectations are right. @PalumboN let me know if this looks fine to you.
> Updating wollok ts version

- .vscode/launch.json
- package.json
- public/diagram/index.html
- src/commands/repl.ts
- src/index.ts
fixes: #66 #64 #56 
El siguiente codigo:
```wollok
object pepita {
var property energia = 100
var property colores = ["rojo", "amarillo", "azul", manolo]
var property esLoMejorQueHay = true
var property esFuncional = false
method vola(kms) {
energia -= kms * 4
}
}
object manolo {
var property coloresPreferidos = ["naranja", "rojo", "verde"]
}
```
Genera este diagrama:
> Diagrama Dinamico - Canvas size, booleans and collections

- package-lock.json
- package.json
- src/commands/repl.ts
- test/repl.test.ts
En [este PR](https://github.com/uqbar-project/wollok-ts/pull/153/files#diff-9d9322717fe9b101966134cc54128da10d71ebdcbad50cbb33f775c55e64b553L162) se sacaron cosas de más que se necesitaban acá.
Por ahora adapté la lógica en este lugar (ya que era el único que lo usaba), pero lo que necesitamos es pensar bien la API que necesitamos de TS.
> Update wollok-ts v4.0.3

- public/diagram/diagram.js
- public/diagram/index.html
- src/commands/repl.ts
En este PR metemos algunas cositas:
- escuchamos el evento 'error' para que si el REPL no puede levantar el diagrama dinámico en el 3000 te tire un mensaje copado
- de paso, si hay otro tipo de error también mostramos un mensaje
- la alternativa es que le pases un puerto distinto: `--port xxxx` y eso está aclarado en el mensaje de error "copado"
- la página del diagrama hardcodeaba el puerto 3000 con lo cual daba un error de CORS al conectarse con el server (igual lo que iba a hacer era espejar el diagrama del 3000 en otras páginas). Ahora podés tener n REPLs con sus correspondientes diagramas dinámicos, una locura (no se para qué pero se puede)
- y también deshabilitamos mensajes que aparecían cada dos por tres en el REPL diciendo que se conectaba/desconectaba el diagrama dinámico. Esto …
> Fix #58 port already used

- scripts/download-libs.sh
The preinstall script failed on win systems because 'wget' isn't available. So, an easy fix is to replace it with curl, ensuring that with the specified parameters, the desired behavior is maintained.
Something I'd like to point out is that on Windows, to execute the installation script, one would need to use a bash emulator. This is because running sh scripts directly through PowerShell requires some workaround tricks.
> fix: preinstall script (#100)

- package-lock.json
- package.json
- src/commands/repl.ts
- src/services/diagram-generator.ts
- src/utils.ts
- test/diagram.test.ts
- test/repl.test.ts
Fix #108 
Resuelve parte de https://github.com/uqbar-project/wollok-ts-cli/issues/90
- Fix de `const x = 1` y `x = 2` en el REPL
- Fix del candadito en las referencias del REPL en el diagrama
- Me tuve que traer cosas de TS, hay que mejorar la interfaz de linkeo -> Es lo que falta del issue
> Fix repl scopes

- src/index.ts
Se arregla la versión command que estaba tirando unknown en vez del numero correspondiente Por lo que vi, la env variable está definida si y solo si se corre el programa con node, como se corre como binario/executable no la encuentra.
> fix: version command (#99)

- package-lock.json
- package.json
Este PR actualiza a la versión 4.0.6 de wollok-ts y resuelve dos issues: 
- instanciar wkos
- instanciar mixines
> Releasing 0.2.0 & upgrading wollok-ts dependency

- .github/workflows/ci.yml
Recién queriendo generar el nuevo release me di cuenta de que por un error me olvidé de volver a correr el CI para los push, y por ende el merge del PR a master no disparó la actualización de la última versión de wollok-ts-cli. La que quedó era del 4/11 que no tenía algunos arreglos que hice posteriormente (por suerte lo pude confirmar porque me lo bajé y la versión que decía era `0.1.2` y no la `0.2.0`)
> Fix uploading executables for ts-cli in release

- src/commands/run.ts
* Cada vez que se da reload el juego empieza a andar más rápido, debido a que se acumulan los setInterval
* Este fix agrega un clearInterval cada vez que se recibe una desconexión
* Nota: esto no soluciona el caso de que se abran dos solapas
* también se corrige una diferencia en el `setInterval` que llama a `flushEvent`: el setInterval se ejecutaba cada 100ms, pero el timer que se pasaba a wollok incrementaba en 300 ms, esto provocaba que los `onTick` no se ejecuten correctamente
> fix: duplicated flushEvent on reload

- examples/init-examples/existing-folder/package.json
- examples/test-examples/normal-case/test-one.wtest
- src/commands/test.ts
- test/test.test.ts
Relacionado a https://github.com/uqbar-project/wollok-lsp-ide/issues/156 cambia como se usan las opciones file/describe/test para que en vez de convertirlo en un fqn recorra el AST para encontrar un test exacto
Usado por https://github.com/uqbar-project/wollok-lsp-ide/pull/158
> Test options exact match

- test/run.test.ts
Probando el PR de Ivo corrí los tests y me saltó este error:
Esto es porque hay un proyecto de ejemplo que tiene el path de la imagen apuntando a `smalls/1.png` y para adaptarlo a Windows tendríamos que generarlo en base al sistema operativo. Con el update simplemente asumo que usamos la barra porque el proyecto está en Linux/Mac y ya. Con lo que da que pensar, no? si dos personas laburan en un proyecto de game en distintos sistemas operativos (uno Windows) cómo se hace.
> Fix windows tests

- examples/init-examples/existing-folder/.gitignore
- src/commands/init.ts
- test/init.test.ts
El wollok init ahora agrega un archivo gitignore:
```bash
.history
*.log
```
para evitar conflictos en un trabajo grupal: va a ser problemático porque cada une tiene su propio log.
> Fix #173 - add gitignore to wollok init

- src/commands/init.ts
- src/index.ts
- src/utils.ts
- test/assertions.ts
- test/init.test.ts
Fix #189
Now the init command has an optional argument for the folder name. 
Me esta creando la carpeta `log` por fuera y no veo donde se crea
> Folder in init `wollok init [folder]`

- src/commands/init.ts
- src/index.ts
- test/init.test.ts
New option for `init` command that initializes a git repository in the freshly created project
If you want to opt out you can pass the --noGit or -ng option.
Usage example:
```sh
wollok init # initializes a git repo
wollok init --noGit # skips the git repo creation
```
This option runs the `git init` command.
~Something that i didn't test is what happens if the user does not have git installed locally.~ Tested and handled
Fixes #122
> Init :: Initialize git repo and new flag `--noGit`

- test/assertions.ts
- test/init.test.ts
Estaba usandose mal cuando hice el pr anterior ya que no se llamaba, cuando intente hacer que falle un test a proposito no me fallo y me levanto todas las alarmas
Inicialmente estaba aca https://github.com/uqbar-project/wollok-ts-cli/pull/193, pero lo saque para priorizar el merge de esto en particular
> Fix de pathAssertion

- examples/init-examples/existing-folder/.github/workflows/ci.yml
- package-lock.json
- src/commands/init.ts
Creo que esto va a quedar mas claro en los CIs porque antes el `wget` generaba un monton de lineas por la descarga y el resultado de los tests quedaban hundidos en esos logs.
> Separate setup and test steps on wollok init CI
